//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguros
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoberturaPorPolizaCliente
    {
        public int FK_IDPolizaPorCliente { get; set; }
        public int FK_IDCobertura { get; set; }
        public int PorcentajeCobertura { get; set; }
    
        public virtual Cobertura Cobertura { get; set; }
        public virtual PolizaPorCliente PolizaPorCliente { get; set; }
    }
}
