//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSeguros
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolizaPorCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PolizaPorCliente()
        {
            this.CoberturaPorPolizaCliente = new HashSet<CoberturaPorPolizaCliente>();
        }
    
        public int ID_PolizaCliente { get; set; }
        public string FK_IDCliente { get; set; }
        public int FK_IDPoliza { get; set; }
        public System.DateTime InicioVigenciaPoliza { get; set; }
        public double PrecioPolizaAdquirida { get; set; }
        public int MesesCobertura { get; set; }
        public int Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoberturaPorPolizaCliente> CoberturaPorPolizaCliente { get; set; }
        public virtual Poliza Poliza { get; set; }
    }
}
